INSERT INTO TEST VALUES(12, 'D');
INSERT INTO TEST VALUES(1, 'A');
INSERT INTO TEST VALUES(15, 'V');
INSERT INTO TEST VALUES(87, 'C');
INSERT INTO TEST VALUES(33, 'L');
INSERT INTO TEST VALUES(46, 'I');
